// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuXYOviuF5VC2onbN1vT-Stu0yfuIpqA',
    appId: '1:783567230580:web:a92e1e2c3b55ca20a06321',
    messagingSenderId: '783567230580',
    projectId: 'chatjpt-b29c2',
    authDomain: 'chatjpt-b29c2.firebaseapp.com',
    storageBucket: 'chatjpt-b29c2.firebasestorage.app',
    measurementId: 'G-4RWZ68SBHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMH4-7ztT7u7Pm-Tnr5bZhUr-iRNXqM48',
    appId: '1:783567230580:android:0b740be5d5f54ce7a06321',
    messagingSenderId: '783567230580',
    projectId: 'chatjpt-b29c2',
    storageBucket: 'chatjpt-b29c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCf9elEN7gpXoa_cRK3S2L5eCAGRLfqQ',
    appId: '1:783567230580:ios:12a42935ab06e6e7a06321',
    messagingSenderId: '783567230580',
    projectId: 'chatjpt-b29c2',
    storageBucket: 'chatjpt-b29c2.firebasestorage.app',
    iosBundleId: 'com.example.chatjpt',
  );

}